### ISSUE TITLE
Example thesis checked in

### ISSUE THREAD

**Issue by jackonelli** [E2-PhD-Council/ThesisTemplate#13]
- Example thesis checked in? As long as we only push updates _not_ in `YourThesis` then it should be fine to auto merge with upstream. Would be nice to test though...

 - Remove `YourThesis/*` from `.gitignore`? Forking git users will be annoyed that their changes aren't noticed? I mean, we should be very careful with making changes in the example thesis folder since that will break auto merge?

**Comment by frehage** [comment]
Definitely agree with point 2 but I do not understand point 1. 

Do you mean that we should separate the pure template files in `YourThesis` from the example material with a new folder called `ExampleThesis`?
