### ISSUE TITLE
Example thesis triggers error

### ISSUE THREAD

**Issue by jackonelli** [E2-PhD-Council/ThesisTemplate#25]
```bash
! Package ThesisTemplate Error: Definition of ``TheCoverPageSubtitle`` and ``Th
eSubtitle`` is inconsistent.

See the ThesisTemplate package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.50 ...le ``TheSubtitle`` is empty or undefined.}
```

I'm not sure of the intended behaviour @frehage but simply defining `TheSubtitle` is a quick fix, I'll push that for the release.

**Comment by frehage** [comment]
This is not a bug. It is part of a custom error handling. The idea is to let the user know that they have an inconsistency in there defined config variables. Your fix is correct and ensures that the template follows the intended behavior :)
