### ISSUE TITLE
Preview not reproducable

### ISSUE THREAD

**Issue by santa-klaus** [E2-PhD-Council/ThesisTemplate#28]
When I compile the template, my pdf output looks different from the included preview file. As far as I can see only the cover page is affected, so it's probably not important. However, I am still curious why this happens.

![grafik](https://user-images.githubusercontent.com/10899463/98110495-7797c300-1e9f-11eb-9feb-f1ad33ba5f50.png)

My file on the left, the included on the right.

**Comment by frehage** [comment]
The included preview (on the right) is produced using the licentiate thesis template, hence the light blue background.
