### ISSUE TITLE
Page 3 needs to be updated to ISBN instead of ISSN

### ISSUE THREAD

**Issue by ashfaqfarooqui** [E2-PhD-Council/ThesisTemplate#38]
According to [these guidelines](https://intranet.chalmers.se/en/tools-support/doctoral-studies-support/doctoral-thesis-defence/thesis-layout/) page 3 needs to be updated to include:
- ISBN,
- Doktorsavhandlingar vid Chalmers tekniska högskola, Ny series nr xxxx'
- Printing company is now called chalmersdigitaltryck, if I am not mistaken.

**Comment by frehage** [comment]
addressed by pull request #40.
